#!/bin/bash

# decrypt file using openssl (key based symmetric ciphers)
# Usage: bash decrypt file

file="$1"
plain=${file%.enc}

# ensure that input is not empty
if [ -z "$file" ]; then
  echo "decrypt: missing input"
  exit 1
fi

# ensure that no existing file is overwritten
if [ -f "./$plain" ]; then
  echo "decrypt: cannot create ‘$plain’ - file exists"
  exit 1
fi

echo "enter password:"

var=$((openssl enc -in $file -d -aes-256-cbc -pass stdin > $plain) 2>&1 >/dev/null)
if [[ $var == *"bad decrypt"* ]]; then
  echo "decrypt: bad decrypt due to wrong password"
  rm $plain
  exit 1
else
  rm $file
fi
