#!/bin/bash

# encrypt file using openssl (key based symmetric ciphers)
# Usage: bash encrypt file

file="$1"

openssl enc -in $file -aes-256-cbc -pass stdin > $file.enc
echo "make sure you remember your password"
rm $file
